# fly.toml app configuration file generated for abra-elixir on 2023-06-18T13:09:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "abra-elixir"
primary_region = "mad"
kill_signal = "SIGTERM"

[env]
  PHX_HOST = "abra-elixir.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 1
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
